live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[font]
size = 16.0

[font.bold]
family = "SF Mono Square"
style = "Bold"

[font.normal]
family = "SF Mono Square"
style = "Regular"

[font.offset]
y = 1

[[keyboard.bindings]]
chars = "\u001B"
key = "LBracket"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "+"
mods = "Shift"

[window]
opacity = 0.9
