live_config_reload = true

import = ["~/.config/alacritty/themes/themes/tokyo-night-storm.toml"]

[font]
size = 16.0
normal = { family = "HackGen35 Console NF", style = "Regular" }
bold = { family = "HackGen35 Console NF", style = "Bold" }
italic = { family = "HackGen35 Console NF", style = "Regular" }
bold_italic = { family = "HackGen35 Console NF", style = "Bold" }

[font.offset]
y = 1

[[keyboard.bindings]]
chars = "\u001B"
key = "LBracket"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "+"
mods = "Alt"

[window]
opacity = 1.0
blur = false

[env]
TERM = "xterm-256color"
