command_timeout=2000
[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
[package]
disabled = true
[kubernetes]
format = 'on [⛵ $context \($namespace\)]($style) '
style = "bold green"
disabled = false
[aws]
format = "on [$symbol$profile]($style) "
style = "bold blue"
[gcloud]
disabled = true
[directory]
truncation_length = 100
truncate_to_repo = false
